version: '3.8'

services:
  measurement_db:
    image: postgres:latest
    container_name: measurement_db
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: measurement_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - measurement_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  measurement_db_data:
